kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/unknowntpo/todos
steps:
  - name: test
    image: golang
    commands:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - make vendor
      - make audit
  - name: build
    image: golang
    commands:
      - make build/api
      - chmod +x ./bin/api
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - '*.go'
      required: true
  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts:
        from_secret: deploy_host
      port:
        from_secret: deploy_port
      user:
        from_secret: deploy_user
      key:
        from_secret: deploy_key
      source: /go/src/github.com/unknowntpo/todos
      target: ~/deploy
      exclude:
        - README.md
      recursive: true
      delete: true
      script:
        - cd ~/deploy/todos
        - make run/compose/up -d
