kind: pipeline
name: default
workspace:
  base: /go
  path: src/github.com/unknowntpo/todos
steps:
  - name: test
    image: golang
    commands:
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - make vendor
        #- make audit
  - name: build
    image: golang
    commands:
      - make build/api
      - chmod +x ./bin/api
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - '*.go'
      required: true
  - name: deploy
    image: alpine
    environment:
      DRONE_DEPLOY_HOST:
        from_secret: deploy_host
      DRONE_DEPLOY_USERNAME:
        from_secret: deploy_user
    commands:
      - docker context create remote ‐‐docker “host=ssh://$(DRONE_DEPLOY_HOST)@$(DRONE_DEPLOY_USERNAME)”
      - make run/compose/up
