kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm
node:
  machine: rpi
workspace:
  base: /go
  path: src/github.com/unknowntpo/todos
steps:
  - name: test
    image: golang:alpine
    commands:
      #- apk add --no-cache make
      #- go install honnef.co/go/tools/cmd/staticcheck@latest
      #- make vendor
      #- make audit
  - name: build
    image: golang:alpine
    commands:
      #- make build/api
      #- chmod +x ./bin/api
  - name: push-image
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run
    secrets: [ docker_username, docker_password ]
    commands:
      - echo "test username"
      - echo $${DOCKER_USERNAME}
      - apk add --no-cache make
      - docker ps -a
      - make image/build/server
      - make image/build/config
      # Ref: https://0-8-0.docs.drone.io/manage-secrets/
      - docker login --username $${DOCKER_USERNAME} --password $${DOCKER_PASSWORD}
      - make image/push/server
      - make image/push/config
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov_token
      files:
        - '*.go'
      required: true
  #  - name: deploy
#    image: docker:dind
#    privileged: true
#    environment:
#      DRONE_DEPLOY_HOST:
#        from_secret: deploy_host
#      DRONE_DEPLOY_USERNAME:
#        from_secret: deploy_user
#    volumes:
#      - name: dockersock
#        path: /var/run
#    commands:
#      - sleep 30 # give docker enough time to initialize
#      - docker ps -a
#      - echo $${DRONE_DEPLOY_HOST}
#      - echo $${DRONE_DEPLOY_USERNAME}
#      - docker context create remote --docker "host=ssh://$${DRONE_DEPLOY_HOST}@$${DRONE_DEPLOY_USERNAME}"
#      # - make run/compose/up
#      # todo fetch from docker hub
#      - DOCKER_BUILDKIT=1 docker-compose \
#        -f docker-compose-prod.yml \
#        --project-name todos-prod \
#        build --parallel
#      - docker-compose -f docker-compose-prod.yml \
#        --context remote \
#        --env-file .envrc \
#        up \
#        -d \
#        --remove-orphans \
#        --force-recreate

# Specify docker:dind as a service
# Ref: https://github.com/testcontainers/dind-drone-plugin
services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  detach: true
volumes:
  - name: dockersock
    temp: {}
