version: "2.3"
services:
  it-test:
    image: testapi
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: it-test
    env_file:
      - ./.envrc
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      config:
        condition: service_healthy
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todos"]
      interval: 10s
      timeout: 5s
      retries: 5
  config:
    image: config
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: config
    healthcheck:
      test: ["CMD-SHELL", "psql $$TODOS_DB_DSN -c SELECT * FROM tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.envrc
    depends_on:
      db:
        condition: service_healthy
