version: "2.3"
services:
  server:
    image: api
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    volumes:
        - /tmp/app:/var/log/app
    env_file:
      - ./.envrc
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    restart: always
    #volumes:
    #  - ./testdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # config will be in charge of:
  # 1. create new user: todos for db.
  # 2. Do sql migrations to db.
  # 3. dump testdata to db.
  config:
    image: alpine
    build:
      context: .
      dockerfile: docker/config/Dockerfile
    env_file:
      - ./.envrc
    depends_on:
      db:
        condition: service_healthy
