version: "2.3"
services:
  server:
    container_name: todos_prod-server
    image: unknowntpo/todos-production-server
  db:
    container_name: todos_prod-db
    image: postgres:alpine
    restart: always
  config:
    container_name: todos_prod-config
    image: unknowntpo/todos-config
networks:
  default:
    name: todos_prod-network
# TODO: Use docker stack deploy to deploy services to production environment
