version: "2.3"
services:
  db:
    container_name: todos_devdb
    image: postgres:alpine
    restart: always
    env_file:
      - ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  config:
    image: alpine
    build:
      context: .
      dockerfile: docker/config/Dockerfile
    env_file:
      - ./.envrc
    depends_on:
      db:
        condition: service_healthy
