version: "2.3"
services:
  it-test:
    image: testapi
    build:
      context: .
      dockerfile: docker/integration-test/Dockerfile
    env_file:
      - ./.envrc
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      config:
        condition: service_started
  db:
    image: postgres:alpine
    restart: always
    env_file:
      - ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  config:
    image: alpine
    build:
      context: .
      dockerfile: docker/config/Dockerfile
    env_file:
      - ./.envrc
    depends_on:
      db:
        condition: service_healthy
