version: "2.3"
services:
  server:
    volumes:
        - /tmp/app:/var/log/app
    env_file:
      - ./.envrc
    ports:
      - "4000:4000"
    depends_on:
      config:
        condition: service_healthy
      db:
        condition: service_healthy
  db:
    restart: always
    env_file:
      - ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  config:
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "psql $$TODOS_APP_DB_DSN -c SELECT * FROM tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.envrc
    depends_on:
      db:
        condition: service_healthy
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui:v4.0.0
    volumes:
      - ./docs:/docs
    env_file:
      - ./.envrc
    ports:
      - "8090:8080"
networks:
  default:
