version: "3"

services:
  server:
    container_name: todos_dev-server
    image: dev-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev-server
    env_file:
      - ./.envrc
  db:
    container_name: todos_dev-db
    env_file:
      - ./.envrc
networks:
  backend:
    name: todos_dev-backend
