version: "2.3"
services:
  server:
    container_name: todos_prod-server
    image: api
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: production
    volumes:
        - /tmp/app:/var/log/app
    env_file:
      - ./.envrc
    ports:
      - "4000:4000"
    depends_on:
      config:
        condition: service_healthy
      db:
        condition: service_healthy
  db:
    container_name: todos_prod-db
    image: postgres:alpine
    restart: always
    #volumes:
    #  - ./testdata/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  config:
    container_name: todos_config
    image: config
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: config
    healthcheck:
      test: ["CMD-SHELL", "psql $$TODOS_APP_DB_DSN -c SELECT * FROM tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - ./.envrc
    depends_on:
      db:
        condition: service_healthy
