version: "2.3"

services:
  server:
    container_name: todos_dev-server
    image: dev-server
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: dev-server
    env_file:
      - ./.envrc
  db:
    container_name: todos_dev-db
    env_file:
      - ./.envrc
  config:
    container_name: todos_dev-config
    image: dev-config
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: config
    env_file:
      - ./.envrc
networks:
  backend:
