version: "2.3"
services:
  server:
    container_name: todos_prod-server
    image: unknowntpo/todos-production-server
  db:
    container_name: todos_prod-db
  config:
    container_name: todos_prod-config
    image: unknowntpo/todos-config
networks:
  backend:
    name: todos_prod-backend
