app:
  port: 4000
  env: production
  db:
    dsn: "postgres://todos:pa55word@db/todos?sslmode=disable"
    max_open_conns: 25
    max_idle_conns: 25
    max_idle_time: 15m
  limiter:
    rps: 2
    burst: 4
    enabled: True
  smtp:
    host: "smtp.mailtrap.io"
    port: 25
    username: "bd2857ac6e1116"
    password: "6f9845a2b11721"
    sender: "TODOs <no-reply@todos.unknowntpo.net>"
  cors:
    trusted_origins:
      - localhost:8080

# TODOS_DB_DSN is used by containers.
#TODOS_DB_DSN='postgres://todos:pa55word@db/todos?sslmode=disable'

# TODOS_DB_DSN_LOCAL is used by local program without using containers.
#TODOS_DB_DSN_LOCAL='postgres://todos:pa55word@localhost/todos?sslmode=disable'
