/*
 * TODOS API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Metadata struct {
	CurrentPage int32 `json:"current_page,omitempty"`
	PageSize int32 `json:"page_size,omitempty"`
	FirstPage int32 `json:"first_page,omitempty"`
	LastPage int32 `json:"last_page,omitempty"`
	TotalRecords int32 `json:"total_records,omitempty"`
}
