/*
 * TODOS API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Task struct {
	Title string `json:"title,omitempty"`
	Content string `json:"content,omitempty"`
	UserId int32 `json:"user_id,omitempty"`
	Done bool `json:"done,omitempty"`
	Version int32 `json:"version,omitempty"`
}
