/*
 * TODOS API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HealthcheckResponse struct {
	Status string `json:"status"`
	Environment string `json:"environment"`
	Version string `json:"version"`
}
