/*
 * TODOS API
 *
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * API version: 0.1.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	Id string `json:"id"`
	CreatedAt string `json:"created_at"`
	Name string `json:"name"`
	Email string `json:"email"`
	Activated bool `json:"activated"`
}
