basePath: /
definitions:
  api.AuthenticationRequestBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  api.AuthenticationResponse:
    properties:
      token:
        $ref: '#/definitions/domain.Token'
    type: object
  api.HealthcheckResponse:
    properties:
      environment:
        type: string
      status:
        type: string
      version:
        type: string
    type: object
  domain.Token:
    properties:
      expiry:
        type: string
      token:
        type: string
    type: object
host: localhost:4000
info:
  contact: {}
  description: This is the api documentation of TODOS server.
  title: TODOS API
  version: "1.0"
paths:
  /v1/healthcheck:
    get:
      description: None.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthcheckResponse'
      summary: Show status of service.
  /v1/tokens/authentication:
    post:
      consumes:
      - application/json
      description: None.
      parameters:
      - description: authentication request body
        in: body
        name: authentication_request_body
        required: true
        schema:
          $ref: '#/definitions/api.AuthenticationRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.AuthenticationResponse'
      summary: Create authentication token for user.
swagger: "2.0"
