basePath: /
definitions:
  api.AuthenticationRequestBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  api.AuthenticationResponse:
    properties:
      token:
        $ref: '#/definitions/domain.Token'
    type: object
  api.GetAllTasksResponse:
    properties:
      metadata:
        $ref: '#/definitions/domain.Metadata'
      tasks:
        items:
          $ref: '#/definitions/domain.Task'
        type: array
    type: object
  api.HealthcheckResponse:
    properties:
      environment:
        type: string
      status:
        type: string
      version:
        type: string
    type: object
  domain.Metadata:
    properties:
      current_page:
        type: integer
      first_page:
        type: integer
      last_page:
        type: integer
      page_size:
        type: integer
      total_records:
        type: integer
    type: object
  domain.Task:
    properties:
      content:
        description: task content
        type: string
      done:
        description: true if task is done
        type: boolean
      id:
        description: Unique integer ID for the task
        type: integer
      title:
        description: task title
        type: string
      version:
        description: The version number starts at 1 and will be incremented each
        type: integer
    type: object
  domain.Token:
    properties:
      expiry:
        type: string
      token:
        type: string
    type: object
  helpers.ErrorResponse:
    type: object
host: localhost:4000
info:
  contact: {}
  description: This is the api documentation of TODOS server.
  title: TODOS API
  version: "1.0"
paths:
  /v1/healthcheck:
    get:
      description: None.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthcheckResponse'
      summary: Show status of service.
  /v1/tasks:
    get:
      consumes:
      - application/json
      parameters:
      - description: User Id
        in: query
        name: userId
        required: true
        type: integer
      - description: title filter
        in: query
        name: title
        type: string
      - description: sort filter
        in: query
        name: sort
        type: string
      - description: id filter
        in: query
        name: id
        type: string
      - description: page filter
        in: query
        name: page
        type: string
      - description: page size filter
        in: query
        name: page_size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.GetAllTasksResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ErrorResponse'
      summary: Gets all tasks for specific user.
  /v1/tokens/authentication:
    post:
      consumes:
      - application/json
      description: None.
      parameters:
      - description: authentication request body
        in: body
        name: authentication_request_body
        required: true
        schema:
          $ref: '#/definitions/api.AuthenticationRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.AuthenticationResponse'
      summary: Create authentication token for user.
swagger: "2.0"
